<?php
/**
 * Module styles trait for Lesson Meta.
 *
 * Wires Divi's design controls (spacing, background, fonts, etc.)
 * to the semantic selectors produced by LessonMetaRenderer.
 *
 * @package LeadersPath\Modules\LessonMeta
 * @since   0.4.0
 */

declare(strict_types=1);

namespace LeadersPath\Modules\LessonMeta\LessonMetaTrait;

use ET\Builder\FrontEnd\Module\Style;
use ET\Builder\Packages\Module\Options\Css\CssStyle;

if ( ! defined( 'ABSPATH' ) ) {
	die( 'Direct access forbidden.' );
}

trait ModuleStylesTrait {

	/**
	 * Generate styles for the Lesson Meta module.
	 *
	 * @since 0.4.0
	 *
	 * @param array $args Style arguments from Divi.
	 * @return void
	 */
	public static function module_styles( array $args ): void {
		$attrs       = $args['attrs'] ?? [];
		$elements    = $args['elements'];
		$settings    = $args['settings'] ?? [];
		$order_class = $args['orderClass'] ?? '';

		// Divi's Layout panel generates flex/grid properties but NOT the
		// display property (that relies on .et_flex_* classes). Our <dl>
		// doesn't carry those classes, so we output display ourselves.
		$list_display  = $attrs['list']['decoration']['layout']['desktop']['value']['display'] ?? 'flex';
		$list_selector = "{$order_class} .leaderspath_lesson_meta__list";

		Style::add( [
			'id'            => $args['id'],
			'name'          => $args['name'],
			'orderIndex'    => $args['orderIndex'],
			'storeInstance' => $args['storeInstance'],
			'styles'        => [
				// Module wrapper (background, spacing, border, etc.).
				$elements->style( [
					'attrName'   => 'module',
					'styleProps' => [
						'disabledOn' => [
							'disabledModuleVisibility' => $settings['disabledModuleVisibility'] ?? null,
						],
					],
				] ),

				// List <dl> layout controls (flex/grid gap, direction, etc.).
				$elements->style( [ 'attrName' => 'list' ] ),

				// Display property for <dl> — not generated by Layout panel.
				// Wrapped in outer array to match $elements->style() 2D format.
				[
					[
						'selector'    => $list_selector,
						'declaration' => "display: {$list_display};",
					],
				],

				// Label <dt> font controls.
				$elements->style( [ 'attrName' => 'label' ] ),

				// Duration <dd> font controls.
				$elements->style( [ 'attrName' => 'duration' ] ),

				// Difficulty <dd> font controls.
				$elements->style( [ 'attrName' => 'difficulty' ] ),

				// Activities <dd> font controls.
				$elements->style( [ 'attrName' => 'activities' ] ),

				// Custom CSS fields.
				CssStyle::style( [
					'selector'  => $order_class,
					'attr'      => $attrs['css'] ?? [],
					'cssFields' => self::custom_css(),
				] ),
			],
		] );
	}
}
